os: osx
osx_image:xcode13.4
language: swift
script: xcodebuild clean build test -project PackageTracker/PackageTracker.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.5,name=iPhone 12" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
